version: '3.8'

services:
  api01: &api
    build: .
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 120M
    command: "sanic server --host=0.0.0.0 --port=8000 --single-process"
    restart: unless-stopped

  api02:
    <<: *api

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "60MB"

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha_2024
    volumes:
      - ./sql.sql:/docker-entrypoint-initdb.d/sql.sql
    command: postgres -c shared_buffers=384MB -c max_connections=400 -c log_min_messages=FATAL
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --dbname=rinha_2024 --username=postgres"
        ]
      interval: 2s
      timeout: 2s
      retries: 30
    restart: unless-stopped
