version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api01:
        condition: service_started
      api02:
        condition: service_started
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50M"

  api01: &api
    build: .
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100M"
    command: "sanic server --host=0.0.0.0 --port=8000 --single-process"
    restart: unless-stopped

  api02:
    <<: *api

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/db/init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.docker/db/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: "300M"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --dbname=rinha_2024 --username=postgres"
        ]
      interval: 2s
      timeout: 2s
      retries: 30
    restart: unless-stopped

volumes:
  postgres_data:
